//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bookclubEntities : DbContext
    {
        public bookclubEntities()
            : base("name=bookclubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clubbook> clubbooks { get; set; }
        public virtual DbSet<club> clubs { get; set; }
        public virtual DbSet<meeting> meetings { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<userbook> userbooks { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
