//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clubbook
    {
        public int clubid { get; set; }
        public string gbid { get; set; }
        public bool isread { get; set; }
    
        public virtual club club { get; set; }
    }
}
