//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting
    {
        public int meetingid { get; set; }
        public Nullable<int> clubid { get; set; }
        public string meetingname { get; set; }
        public string description { get; set; }
        public string bookid { get; set; }
        public Nullable<System.DateTime> meetingtime { get; set; }
    
        public virtual club club { get; set; }
    }
}
