//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userbook
    {
        public int userid { get; set; }
        public string gbid { get; set; }
        public bool isread { get; set; }
        public string reviewbody { get; set; }
        public Nullable<int> urating { get; set; }
    
        public virtual user user { get; set; }
    }
}
